### ISSUE TITLE
Question: is a JIT-ed `Trampoline` method large enough to be overwritten?

### ISSUE THREAD

**Issue by tandasat** [airbus-cert/PSTrace#1]
The assembly code JIT-ed from the `Trampoline` method is going to be overwritten with a hook (JMP instructions etc). If the JIT-ed code is smaller than the hook instructions, it is going to overwrite unrelated memory which can result in application crash if the overwritten memory is referenced. 

When I did my research, this was an actual problem and I needed to insert more instructions as explicitly stated here: https://github.com/tandasat/DotNetHooking/blob/master/HookingAssembly/HookingAssembly/HookingAssembly.cs#L244

Did you verify JIT-ed code is large enough for both x64 and x86?

**Comment by citronneur** [comment]
Hi Satoshi,

First of all, thanks for your work.

Indeed I have the same issue. During first step of development of PSTrace, i used detours as hooking library, but the trampoline method was very big. It's why i read your work and use Minhook like you. 

I put an exception code that generate enough code for trampoline, exactly like you, for the two methods that we hooked for x86 and x64.

Thanks again.

**Comment by tandasat** [comment]
The exception wasn’t large enough (on Release x64 probably) when I worked on this but sounds like it changed in the last couple of years. 

Thanks for confirmation.
